%% Import data from text file.
% Script for importing data from the following text file:
%
%    /home/jakub/Studia/6_Semestr/SNB/Projekt/3d_spheres/data.csv
%
% To extend the code to different selected data or a different text file, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/04/08 13:39:51

%% Initialize variables.
filename = 'data.csv';
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Allocate imported array to column variable names
%target = dataArray{:, 1};
x = dataArray{:, 2};
y = dataArray{:, 3};
z = dataArray{:, 4};

xT1 = x(2:2501, :);
yT1 = y(2:2501, :);
zT1 = z(2:2501, :);
xT2 = x(2502:end, :);
yT2 = y(2502:end, :);
zT2 = z(2502:end, :);

figure();
scatter3(xT1,yT1,zT1, 2, 'k');
hold on;
scatter3(xT2,yT2,zT2, 2, 'r');
%hold off;
%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans;